services:
  projarc-database:
    container_name: projarc-database
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sale-system
    ports:
      - '5432:5432'
    volumes:
      - sale-system-data:/var/lib/postgresql/data

volumes:
  sale-system-data:
